package Creational.Factory.AfterFactory;

public enum TYPE {
    PAYMENT,
    REFUND,
    ONLINE_PAYMENT,
    OFFLINE_PAYMENT,
    CASH_PAYMENT,
    CREDIT_CARD_PAYMENT,
    DEBIT_CARD_PAYMENT,
    PAYPAL_PAYMENT,
    BANK_TRANSFER_PAYMENT,
    MOBILE_WALLET_PAYMENT,
    UPI_PAYMENT,
    CRYPTOCURRENCY_PAYMENT,
    GIFT_CARD_PAYMENT,
    REWARD_POINTS_PAYMENT,
    INVOICE_PAYMENT,
    SUBSCRIPTION_PAYMENT,
    INSTALLMENT_PAYMENT,
}
